
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cafekiosk
    username: root
    password: 1234

  jpa: # jpa?? ??
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
